name: Deploy Aerobro

on:
  push:
    tags:
      - '*'

jobs:
  upload_aerobro:
    name: Upload Aplikasi Aerobro
    runs-on: server15

    steps:
      - name: Checkout Latest Version
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create Env
        run: |
          cat > .env << ENDOFFILE
          DEBUG=release
          SECRET_KEY=${{ secrets.SECRET_KEY }}
          DB_USERNAME=${{ secrets.DB_USER }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          DB_NAME=${{ secrets.DB_NAME }}
          DB_HOST=${{ secrets.DB_HOST }}
          DB_PORT=${{ secrets.DB_PORT }}
          ENDOFFILE

      - name: Run Migration
        run: |
          python3 manage.py migrate --fake-initial
