name: Deploy Aerobro

on:
  push:
    tags:
      - '*'

jobs:
  upload_aerobro:
    name: Upload Aplikasi Aerobro
    runs-on: server15
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.7, 3.8, 3.9 ]

    steps:
      - name: Checkout Latest Version
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create Env
        run: |
          cat > .env << ENDOFFILE
          DEBUG=release
          SECRET_KEY=${{ secrets.SECRET_KEY }}
          DB_USERNAME=${{ secrets.DB_USER }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          DB_NAME=${{ secrets.DB_NAME }}
          DB_HOST=${{ secrets.DB_HOST }}
          DB_PORT=${{ secrets.DB_PORT }}
          ENDOFFILE

      - name: Run Migration
        run: |
          python manage.py migrate --fake-initial
